# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usb_storage" "sd_mod" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/partitions-fsroot";
      fsType = "btrfs";
      options = "discard";
    };

  fileSystems."/home" =
    { device = "/dev/mapper/partitions-home";
      fsType = "btrfs";
      options = "discard";
    };

  fileSystems."/var/lib/docker" =
    { device = "/dev/mapper/partitions-home";
      fsType = "btrfs";
      options = "subvol=docker";
    };

  fileSystems."/boot" =
    { device = "/dev/sda1";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/mapper/partitions-swap"; }
    ];

  nix.maxJobs = lib.mkDefault 4;
}
